name: kookers
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

# dart pub outdated --mode=null-safety verify if all 
version: 1.1.3+12

environment:
  sdk: ">=2.7.0 <3.0.0"

dependency_overrides:
   intl: ^0.17.0-nullsafety.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: # Add this line
    sdk: flutter         

  
  graphql_flutter: ^3.1.0
  intl: ^0.16.1
  graphql: ^3.0.0
  stripe_payment: ^1.0.9
  google_fonts: ^1.1.1
  modal_bottom_sheet: ^1.0.0+1
  chips_choice: ^2.0.1
  enum_to_string: ^1.0.14
  flutter_rating_bar: ^3.2.0+1
  circular_check_box: ^1.0.4
  flutter_chat_bubble: ^1.0.2
  toggle_switch: ^0.1.8
  country_code_picker: ^1.7.0
  flutter_svg: ^0.19.1
  carousel_slider: ^2.3.1
  firebase_core: "^0.7.0"
  firebase_auth: ^0.20.0+1
  firebase_analytics: "^7.0.1"
  firebase_crashlytics: "^0.4.0+1"
  firebase_performance: "^0.5.0+1"
  firebase_messaging: "^8.0.0-dev.14"
  firebase_storage: "^7.0.0"
  provider: "^4.3.2+1"
  google_maps_flutter: ^0.5.28+1
  shimmer: ^1.1.2
  google_place: ^0.3.3
  cached_network_image: ^2.5.0
  image_picker: ^0.6.7+22
  rxdart: ^0.24.1
  uuid: ^2.2.2
  dart_geohash: ^1.0.2
  pull_to_refresh: ^1.6.3
  lottie: ^0.7.0+1
  currency_pickers: ^1.0.6
  photo_view: ^0.10.3
  keyboard_actions: ^3.3.1+1
  url_launcher: ^5.7.10
  rate_my_app: ^0.7.2
  jiffy: ^3.0.1
  iban: ^0.2.1
  flutter_app_badger: ^1.1.2
  badges: ^1.1.6
  package_info: ^0.4.3+4
  webview_flutter: ^1.0.7
  flutter_native_image: ^0.0.5+3
  get: ^3.25.4
  permission_handler: ^5.0.1+1



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  integration_test: ^1.0.1
  flutter_launcher_icons: ^0.8.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter_icons:
  image_path: 'assets/logo/logo_flutter_white.jpg'
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/payments_logo/
   - assets/onboarding/
   - assets/logo/
   - assets/lottie/
   - assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
